# Generated by Django 3.2 on 2021-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('genre', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
