# Generated by Django 3.2 on 2021-04-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_desc_movie_summary_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='summary_text',
            new_name='desc',
        ),
    ]
